### ISSUE TITLE
Get familiar with hashing file contents in Python

### ISSUE THREAD

**Issue by mwatts15** [openworm/bt-gsoc-2019#2]
In Python there is hashlib (maybe other libraries). Just need to know how to hash files, verify hashes, and how hash collisions can happen

Exit criteria:
- [ ] Know how to hash with one or more algorithms in Python
- [ ] Decide how to hash directories and directory trees vs single files
- [ ] Explain when different files can have the same hash (hash collisions)

**Comment by jaideep-seth** [comment]
Exit Criteria:
- [X] Know how to hash with one or more algorithms in Python
- hashlib module implemented for python can hash in MD4, MD5, SHA1, SHA2 etc..
- [X] Decide how to hash directories and directory trees vs single files
- file_hash() and folder_hash() methods hash single files and directories respectively and these methods are implemented within Uploading/seed_final.py
- [X] Explain when different files can have the same hash (hash collisions)
- Message Digest algorithms like MD5 and SHA use the contents to create a fixed length hash, unless the contents are identical there can be no hash collisions.
