### ISSUE TITLE
Selection of a publicly accessible platform for accessing .torrent files.

### ISSUE THREAD

**Issue by jaideep-seth** [openworm/bt-gsoc-2019#6]
The .torrent file contain details about where and how the uploader's contents are stored on other peers in the P2P BitTorrent network. In-order to download contents one must have access to its .torrent file. Lets call the platform from where the .torrents can be publicly accessible the "Torrent Access Method".

Exit Criteria:
- [x] "Torrent Access Method" must allow users to View, Upload and Download Files.
- [x] "Torrent Access Method" must be publicly available, always available and there must be no cost of maintaining availability.
- [x] "Torrent Access Method" API must be python installable(pip) having no other system dependencies.

**Comment by jaideep-seth** [comment]
After deliberation i have chosen "Google Drive" as the "Torrent Access Method" as:
- [X] Google Drive Python API allows users to View, Upload and Download Files.
- [X] Google Drive is publicly & always available having no maintenance costs.
- [X] Google Drives Python API modules required for Viewing, Uploading & Downloading are installable using only pip, having no other system dependencies.
  
@mwatts15 please let me know if this issue can be closed!

**Comment by mwatts15** [comment]
Looks good to me. You should be able to close issues yourself now as well.
